config/routes.rb
Rails.application.routes.draw do
  resources :student_enrollment_codes
  resources :submissions
  resources :questions
  resources :worksheets
  resources :classrooms
  resources :courses
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :worksheet
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy!

    respond_to do |format|
      format.html { redirect_to questions_path, status: :see_other, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:content, :question_type, :choices, :answer, :rubric, :worksheet_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
  <% if question.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :question_type, style: "display: block" %>
    <%= form.text_field :question_type %>
  </div>

  <div>
    <%= form.label :choices, style: "display: block" %>
    <%= form.text_area :choices %>
  </div>

  <div>
    <%= form.label :answer, style: "display: block" %>
    <%= form.text_area :answer %>
  </div>

  <div>
    <%= form.label :rubric, style: "display: block" %>
    <%= form.text_area :rubric %>
  </div>

  <div>
    <%= form.label :worksheet_id, style: "display: block" %>
    <%= form.text_field :worksheet_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div id="<%= dom_id question %>">
  <p>
    <strong>Content:</strong>
    <%= question.content %>
  </p>

  <p>
    <strong>Question type:</strong>
    <%= question.question_type %>
  </p>

  <p>
    <strong>Choices:</strong>
    <%= question.choices %>
  </p>

  <p>
    <strong>Answer:</strong>
    <%= question.answer %>
  </p>

  <p>
    <strong>Rubric:</strong>
    <%= question.rubric %>
  </p>

  <p>
    <strong>Worksheet:</strong>
    <%= question.worksheet_id %>
  </p>

</div>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Show this question", @question %> |
  <%= link_to "Back to questions", questions_path %>
</div>

app/views/questions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Questions</h1>

<div id="questions">
  <% @questions.each do |question| %>
    <%= render question %>
    <p>
      <%= link_to "Show this question", question %>
    </p>
  <% end %>
</div>

<%= link_to "New question", new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Back to questions", questions_path %>
</div>

app/views/questions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @question %>

<div>
  <%= link_to "Edit this question", edit_question_path(@question) %> |
  <%= link_to "Back to questions", questions_path %>

  <%= button_to "Destroy this question", @question, method: :delete %>
</div>