config/routes.rb
Rails.application.routes.draw do
  resources :student_enrollment_codes
  resources :submissions
  resources :questions
  resources :worksheets
  resources :classrooms
  resources :courses
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/worksheet.rb
class Worksheet < ApplicationRecord
  belongs_to :classroom
  has_many :questions, dependent: :destroy
  has_many :submissions, dependent: :destroy
end

app/controllers/worksheets_controller.rb
class WorksheetsController < ApplicationController
  before_action :set_worksheet, only: %i[ show edit update destroy ]

  # GET /worksheets or /worksheets.json
  def index
    @worksheets = Worksheet.all
  end

  # GET /worksheets/1 or /worksheets/1.json
  def show
  end

  # GET /worksheets/new
  def new
    @worksheet = Worksheet.new
  end

  # GET /worksheets/1/edit
  def edit
  end

  # POST /worksheets or /worksheets.json
  def create
    @worksheet = Worksheet.new(worksheet_params)

    respond_to do |format|
      if @worksheet.save
        format.html { redirect_to @worksheet, notice: "Worksheet was successfully created." }
        format.json { render :show, status: :created, location: @worksheet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @worksheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /worksheets/1 or /worksheets/1.json
  def update
    respond_to do |format|
      if @worksheet.update(worksheet_params)
        format.html { redirect_to @worksheet, notice: "Worksheet was successfully updated." }
        format.json { render :show, status: :ok, location: @worksheet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @worksheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /worksheets/1 or /worksheets/1.json
  def destroy
    @worksheet.destroy!

    respond_to do |format|
      format.html { redirect_to worksheets_path, status: :see_other, notice: "Worksheet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worksheet
      @worksheet = Worksheet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def worksheet_params
      params.require(:worksheet).permit(:title, :classroom_id)
    end
end

app/helpers/worksheets_helper.rb
module WorksheetsHelper
end

app/views/worksheets/_form.html.erb
<%= form_with(model: worksheet) do |form| %>
  <% if worksheet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(worksheet.errors.count, "error") %> prohibited this worksheet from being saved:</h2>

      <ul>
        <% worksheet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :classroom_id, style: "display: block" %>
    <%= form.text_field :classroom_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/worksheets/_worksheet.html.erb
<div id="<%= dom_id worksheet %>">
  <p>
    <strong>Title:</strong>
    <%= worksheet.title %>
  </p>

  <p>
    <strong>Classroom:</strong>
    <%= worksheet.classroom_id %>
  </p>

</div>

app/views/worksheets/edit.html.erb
<h1>Editing worksheet</h1>

<%= render "form", worksheet: @worksheet %>

<br>

<div>
  <%= link_to "Show this worksheet", @worksheet %> |
  <%= link_to "Back to worksheets", worksheets_path %>
</div>

app/views/worksheets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Worksheets</h1>

<div id="worksheets">
  <% @worksheets.each do |worksheet| %>
    <%= render worksheet %>
    <p>
      <%= link_to "Show this worksheet", worksheet %>
    </p>
  <% end %>
</div>

<%= link_to "New worksheet", new_worksheet_path %>

app/views/worksheets/new.html.erb
<h1>New worksheet</h1>

<%= render "form", worksheet: @worksheet %>

<br>

<div>
  <%= link_to "Back to worksheets", worksheets_path %>
</div>

app/views/worksheets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @worksheet %>

<div>
  <%= link_to "Edit this worksheet", edit_worksheet_path(@worksheet) %> |
  <%= link_to "Back to worksheets", worksheets_path %>

  <%= button_to "Destroy this worksheet", @worksheet, method: :delete %>
</div>