config/routes.rb
Rails.application.routes.draw do
  resources :student_enrollment_codes
  resources :submissions
  resources :questions
  resources :worksheets
  resources :classrooms
  resources :courses
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :student, class_name: 'User'
  belongs_to :worksheet
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: %i[ show edit update destroy ]

  # GET /submissions or /submissions.json
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1 or /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions or /submissions.json
  def create
    @submission = Submission.new(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: "Submission was successfully created." }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1 or /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: "Submission was successfully updated." }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1 or /submissions/1.json
  def destroy
    @submission.destroy!

    respond_to do |format|
      format.html { redirect_to submissions_path, status: :see_other, notice: "Submission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def submission_params
      params.require(:submission).permit(:student_id, :worksheet_id, :answers, :grades)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<%= form_with(model: submission) do |form| %>
  <% if submission.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
        <% submission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= form.text_field :student_id %>
  </div>

  <div>
    <%= form.label :worksheet_id, style: "display: block" %>
    <%= form.text_field :worksheet_id %>
  </div>

  <div>
    <%= form.label :answers, style: "display: block" %>
    <%= form.text_field :answers %>
  </div>

  <div>
    <%= form.label :grades, style: "display: block" %>
    <%= form.text_field :grades %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/submissions/_submission.html.erb
<div id="<%= dom_id submission %>">
  <p>
    <strong>Student:</strong>
    <%= submission.student_id %>
  </p>

  <p>
    <strong>Worksheet:</strong>
    <%= submission.worksheet_id %>
  </p>

  <p>
    <strong>Answers:</strong>
    <%= submission.answers %>
  </p>

  <p>
    <strong>Grades:</strong>
    <%= submission.grades %>
  </p>

</div>

app/views/submissions/edit.html.erb
<h1>Editing submission</h1>

<%= render "form", submission: @submission %>

<br>

<div>
  <%= link_to "Show this submission", @submission %> |
  <%= link_to "Back to submissions", submissions_path %>
</div>

app/views/submissions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Submissions</h1>

<div id="submissions">
  <% @submissions.each do |submission| %>
    <%= render submission %>
    <p>
      <%= link_to "Show this submission", submission %>
    </p>
  <% end %>
</div>

<%= link_to "New submission", new_submission_path %>

app/views/submissions/new.html.erb
<h1>New submission</h1>

<%= render "form", submission: @submission %>

<br>

<div>
  <%= link_to "Back to submissions", submissions_path %>
</div>

app/views/submissions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @submission %>

<div>
  <%= link_to "Edit this submission", edit_submission_path(@submission) %> |
  <%= link_to "Back to submissions", submissions_path %>

  <%= button_to "Destroy this submission", @submission, method: :delete %>
</div>