config/routes.rb
Rails.application.routes.draw do
  resources :student_enrollment_codes
  resources :submissions
  resources :questions
  resources :worksheets
  resources :classrooms
  resources :courses
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/student_enrollment_code.rb
class StudentEnrollmentCode < ApplicationRecord
  belongs_to :classroom
  belongs_to :user, optional: true # Assigned after a student uses the code
end

app/controllers/student_enrollment_codes_controller.rb
class StudentEnrollmentCodesController < ApplicationController
  before_action :set_student_enrollment_code, only: %i[ show edit update destroy ]

  # GET /student_enrollment_codes or /student_enrollment_codes.json
  def index
    @student_enrollment_codes = StudentEnrollmentCode.all
  end

  # GET /student_enrollment_codes/1 or /student_enrollment_codes/1.json
  def show
  end

  # GET /student_enrollment_codes/new
  def new
    @student_enrollment_code = StudentEnrollmentCode.new
  end

  # GET /student_enrollment_codes/1/edit
  def edit
  end

  # POST /student_enrollment_codes or /student_enrollment_codes.json
  def create
    @student_enrollment_code = StudentEnrollmentCode.new(student_enrollment_code_params)

    respond_to do |format|
      if @student_enrollment_code.save
        format.html { redirect_to @student_enrollment_code, notice: "Student enrollment code was successfully created." }
        format.json { render :show, status: :created, location: @student_enrollment_code }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student_enrollment_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_enrollment_codes/1 or /student_enrollment_codes/1.json
  def update
    respond_to do |format|
      if @student_enrollment_code.update(student_enrollment_code_params)
        format.html { redirect_to @student_enrollment_code, notice: "Student enrollment code was successfully updated." }
        format.json { render :show, status: :ok, location: @student_enrollment_code }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student_enrollment_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_enrollment_codes/1 or /student_enrollment_codes/1.json
  def destroy
    @student_enrollment_code.destroy!

    respond_to do |format|
      format.html { redirect_to student_enrollment_codes_path, status: :see_other, notice: "Student enrollment code was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_enrollment_code
      @student_enrollment_code = StudentEnrollmentCode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_enrollment_code_params
      params.require(:student_enrollment_code).permit(:classroom_id, :code, :email, :used, :user_id)
    end
end

app/helpers/student_enrollment_codes_helper.rb
module StudentEnrollmentCodesHelper
end

app/views/student_enrollment_codes/_form.html.erb
<%= form_with(model: student_enrollment_code) do |form| %>
  <% if student_enrollment_code.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student_enrollment_code.errors.count, "error") %> prohibited this student_enrollment_code from being saved:</h2>

      <ul>
        <% student_enrollment_code.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :classroom_id, style: "display: block" %>
    <%= form.text_field :classroom_id %>
  </div>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :used, style: "display: block" %>
    <%= form.check_box :used %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/student_enrollment_codes/_student_enrollment_code.html.erb
<div id="<%= dom_id student_enrollment_code %>">
  <p>
    <strong>Classroom:</strong>
    <%= student_enrollment_code.classroom_id %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= student_enrollment_code.code %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= student_enrollment_code.email %>
  </p>

  <p>
    <strong>Used:</strong>
    <%= student_enrollment_code.used %>
  </p>

  <p>
    <strong>User:</strong>
    <%= student_enrollment_code.user_id %>
  </p>

</div>

app/views/student_enrollment_codes/edit.html.erb
<h1>Editing student enrollment code</h1>

<%= render "form", student_enrollment_code: @student_enrollment_code %>

<br>

<div>
  <%= link_to "Show this student enrollment code", @student_enrollment_code %> |
  <%= link_to "Back to student enrollment codes", student_enrollment_codes_path %>
</div>

app/views/student_enrollment_codes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Student enrollment codes</h1>

<div id="student_enrollment_codes">
  <% @student_enrollment_codes.each do |student_enrollment_code| %>
    <%= render student_enrollment_code %>
    <p>
      <%= link_to "Show this student enrollment code", student_enrollment_code %>
    </p>
  <% end %>
</div>

<%= link_to "New student enrollment code", new_student_enrollment_code_path %>

app/views/student_enrollment_codes/new.html.erb
<h1>New student enrollment code</h1>

<%= render "form", student_enrollment_code: @student_enrollment_code %>

<br>

<div>
  <%= link_to "Back to student enrollment codes", student_enrollment_codes_path %>
</div>

app/views/student_enrollment_codes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student_enrollment_code %>

<div>
  <%= link_to "Edit this student enrollment code", edit_student_enrollment_code_path(@student_enrollment_code) %> |
  <%= link_to "Back to student enrollment codes", student_enrollment_codes_path %>

  <%= button_to "Destroy this student enrollment code", @student_enrollment_code, method: :delete %>
</div>